#!/usr/bin/env python3
"""External-package demo: agentsg Niggli reduction through phridge.

Shows the canonical wiring for a third-party science package::

    pip install "git+https://github.com/phzwart/agentsg.git#subdirectory=agentsg"
    # or: pip install -e ".[agentsg]"

    PYTHONPATH=examples python examples/agentsg_cell_reduce.py
    # → examples/agentsg_cell_reduce.md

Production (Redis + worker)::

    PYTHONPATH=examples phridge-worker --preload plugins.agentsg_niggli
    PYTHONPATH=examples python -c "import plugins.agentsg_niggli; ..."
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Sequence

HERE = Path(__file__).resolve().parent
DEFAULT_MD = HERE / "agentsg_cell_reduce.md"

# Allow ``import plugins.agentsg_niggli`` when run as a script.
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

# Triclinic cell that is not already Niggli-reduced (agentsg README example).
INPUT_CELL = (9.0, 5.0, 7.0, 80.0, 100.0, 95.0)


@dataclass
class DemoLog:
    title: str
    checks: list[tuple[bool, str]] = field(default_factory=list)
    sections: list[str] = field(default_factory=list)
    failed: bool = False

    def heading(self, text: str) -> None:
        self.sections.append(f"\n## {text}\n\n")

    def para(self, text: str) -> None:
        self.sections.append(f"{text}\n\n")

    def code(self, source: str, lang: str = "python") -> None:
        self.sections.append(f"```{lang}\n{source.rstrip()}\n```\n\n")

    def output(self, text: str) -> None:
        self.sections.append(f"**Output:**\n\n```text\n{text.rstrip()}\n```\n\n")

    def table(self, headers: list[str], rows: list[list[str]]) -> None:
        self.sections.append("| " + " | ".join(headers) + " |\n")
        self.sections.append("| " + " | ".join("---" for _ in headers) + " |\n")
        for row in rows:
            self.sections.append("| " + " | ".join(row) + " |\n")
        self.sections.append("\n")

    def check(self, ok: bool, label: str, detail: str = "") -> None:
        self.checks.append((ok, label if not detail else f"{label} — {detail}"))
        mark = "PASS" if ok else "FAIL"
        line = f"**{mark}** `{label}`"
        if detail:
            line += f" — {detail}"
        self.sections.append(f"- {line}\n")
        if not ok:
            self.failed = True
        print(f"[{mark}] {label}" + (f" — {detail}" if detail else ""))

    def render(self) -> str:
        stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        n_ok = sum(1 for ok, _ in self.checks if ok)
        n = len(self.checks)
        status = "all checks passed" if n_ok == n and n else f"{n_ok}/{n} checks passed"
        lines = [
            f"# {self.title}\n",
            f"_Generated by `examples/agentsg_cell_reduce.py` on {stamp}. {status}._\n",
            "\n## Summary\n",
            "\n| | |\n|---|---|\n",
            "| Flow | JSON cell → phridge → agentsg `niggli_reduce` → JSON |\n",
            "| External pkg | [agentsg](https://github.com/phzwart/agentsg) |\n",
            "| Op | `agentsg_niggli_reduce` (plugin, not a built-in) |\n",
            f"| Checks | **{n_ok}/{n}** passed |\n",
            f"| Result | **{'OK' if not self.failed else 'FAILED'}** |\n",
            "\n### Checklist\n",
        ]
        for ok, label in self.checks:
            lines.append(f"- [{'x' if ok else ' '}] {label}\n")
        lines.append("\n")
        lines.extend(self.sections)
        return "".join(lines)

    def write(self, path: Path) -> None:
        path.write_text(self.render(), encoding="utf-8")
        print(f"wrote {path}")


def _fmt_cell(cell: Sequence[float]) -> str:
    a, b, c, al, be, ga = (float(x) for x in cell)
    return f"({a:.4g}, {b:.4g}, {c:.4g}, {al:.4g}, {be:.4g}, {ga:.4g})"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_MD)
    args = parser.parse_args(argv)

    log = DemoLog(title="External op: agentsg Niggli reduction via phridge")
    log.heading("Setup")
    log.para(
        "This is the canonical **bring-your-own-package** example. "
        "[agentsg](https://github.com/phzwart/agentsg) is not part of phridge; "
        "a thin plugin under `examples/plugins/` registers "
        "`agentsg_niggli_reduce` with `phridge.ops.register_op`. "
        "Payloads are plain JSON (no new LinkML type)."
    )
    log.code(
        """\
# install once
pip install "git+https://github.com/phzwart/agentsg.git#subdirectory=agentsg"

# plugin (examples/plugins/agentsg_niggli.py)
from phridge.ops import register_op
from agentsg.cell import niggli_reduce

def agentsg_niggli_reduce(cell, params=None):
    reduced, cob = niggli_reduce(*_as_params(cell))
    return {"unit_cell": list(reduced), "change_of_basis": cob, "source": "agentsg"}

register_op("agentsg_niggli_reduce", agentsg_niggli_reduce,
            inputs={"cell": "json", "params": "json"},
            outputs={"result": "json"})
"""
    )

    try:
        import agentsg  # noqa: F401
        from agentsg.cell import niggli_reduce
    except ImportError:
        log.check(False, "agentsg importable", "pip install -e \".[agentsg]\"")
        log.write(args.output)
        return 1
    log.check(True, "agentsg importable", getattr(agentsg, "__version__", agentsg.__name__))

    import plugins.agentsg_niggli  # noqa: F401 — register_op side effect

    from phridge.client import Bridge
    from phridge.ops import get_op

    log.heading("1. Register external op")
    spec = get_op("agentsg_niggli_reduce")
    log.output(f"op={spec.name}\ninputs={spec.inputs}\noutputs={spec.outputs}")
    log.check(spec.name == "agentsg_niggli_reduce", "op registered in catalog")

    log.heading("2. Direct agentsg call (oracle)")
    direct_cell, direct_cob = niggli_reduce(*INPUT_CELL)
    log.para(f"Input cell (not Niggli): `{_fmt_cell(INPUT_CELL)}`")
    log.output(
        f"reduced={_fmt_cell(direct_cell)}\n"
        f"change_of_basis={direct_cob}"
    )

    log.heading("3. Same call through Bridge(memory=True)")
    log.code(
        """\
import plugins.agentsg_niggli  # registers the op
from phridge.client import Bridge

bridge = Bridge(memory=True)
out = bridge.call(
    "agentsg_niggli_reduce",
    cell={"a": 9, "b": 5, "c": 7, "alpha": 80, "beta": 100, "gamma": 95},
)
# out["unit_cell"], out["change_of_basis"]
"""
    )
    log.para(
        "Memory mode uses the same pack → enqueue → `process_envelope` path as a "
        "live worker, without `redis-server`. For a remote GPU/CPU worker::\n\n"
        "```bash\n"
        "PYTHONPATH=examples phridge-worker --preload plugins.agentsg_niggli \\\n"
        "  --redis-url redis://localhost:6379/0\n"
        "```"
    )

    bridge = Bridge(memory=True, timeout=30)
    cell_dict = {
        "a": INPUT_CELL[0],
        "b": INPUT_CELL[1],
        "c": INPUT_CELL[2],
        "alpha": INPUT_CELL[3],
        "beta": INPUT_CELL[4],
        "gamma": INPUT_CELL[5],
    }
    remote: dict[str, Any] = bridge.call("agentsg_niggli_reduce", cell=cell_dict)
    log.output(
        f"unit_cell={_fmt_cell(remote['unit_cell'])}\n"
        f"change_of_basis={remote['change_of_basis']}\n"
        f"source={remote.get('source')}"
    )

    log.heading("4. Phenix-facing wrapper (cctbx in / cctbx out)")
    log.code(
        """\
from cctbx import uctbx
from plugins.agentsg_niggli import niggli_cell
from phridge.client import Bridge

bridge = Bridge(memory=True)
uc = uctbx.unit_cell((9, 5, 7, 80, 100, 95))
uc_red = niggli_cell(uc, bridge=bridge)                 # uctbx.unit_cell
uc_red, cb_op = niggli_cell(uc, bridge=bridge, return_change_of_basis=True)
"""
    )
    from cctbx import uctbx
    from plugins.agentsg_niggli import niggli_cell

    uc_in = uctbx.unit_cell(INPUT_CELL)
    uc_red = niggli_cell(uc_in, bridge=bridge)
    uc_red2, cb_op = niggli_cell(uc_in, bridge=bridge, return_change_of_basis=True)
    log.output(
        f"type(uc_red)={type(uc_red).__module__}.{type(uc_red).__name__}\n"
        f"parameters={tuple(uc_red.parameters())}\n"
        f"cb_op.as_xyz()={cb_op.as_xyz()}"
    )
    log.check(
        isinstance(uc_red, uctbx.unit_cell),
        "niggli_cell returns uctbx.unit_cell",
        type(uc_red).__name__,
    )
    wrap_err = max(
        abs(float(a) - float(b))
        for a, b in zip(uc_red.parameters(), direct_cell)
    )
    log.check(
        wrap_err < 1e-9,
        "wrapper matches agentsg oracle",
        f"max|Δ|={wrap_err:.3g}",
    )
    log.check(
        tuple(uc_red2.parameters()) == tuple(uc_red.parameters()),
        "return_change_of_basis keeps same cell",
    )

    log.heading("5. Checks")
    log.check(remote.get("source") == "agentsg", "result.source is agentsg")
    remote_cell = [float(x) for x in remote["unit_cell"]]
    oracle = [float(x) for x in direct_cell]
    max_err = max(abs(a - b) for a, b in zip(remote_cell, oracle))
    log.check(
        max_err < 1e-9,
        "remote unit_cell matches direct niggli_reduce",
        f"max|Δ|={max_err:.3g}",
    )
    log.check(
        remote["change_of_basis"] == [[int(v) for v in row] for row in direct_cob],
        "change_of_basis matches oracle",
    )
    log.table(
        ["", "a", "b", "c", "α", "β", "γ"],
        [
            ["input", *[f"{x:.4g}" for x in INPUT_CELL]],
            ["agentsg direct", *[f"{x:.4g}" for x in oracle]],
            ["via phridge JSON", *[f"{x:.4g}" for x in remote_cell]],
            ["via niggli_cell()", *[f"{x:.4g}" for x in uc_red.parameters()]],
        ],
    )

    log.heading("Done")
    log.para(
        "Worker stays JSON-only (no cctbx). The Phenix-facing `niggli_cell` "
        "wrapper in `examples/plugins/agentsg_niggli.py` converts "
        "`uctbx.unit_cell` ↔ JSON around `Bridge.call`. See "
        "[docs/extending.md](../docs/extending.md)."
    )
    log.write(args.output)
    return 1 if log.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
