#!/usr/bin/env python3
"""Torch-driven latent Adam with CCTBX restraint E/grads via phridge.

Flow (every science hop through Bridge)::

    RemoteRestraintBuilder.build(pdb)     # CCTBX: live GRM + handle
    scramble xyz → encode → z             # fixed invertible MLP (64-D / residue)
    loop:
        xyz = decode(z)
        E, g_x = geo.energy_and_gradients(xyz)   # CCTBX via phridge
        VJP g_x through decode → Adam on z

    python examples/latent_restraints_adam.py
    # → examples/latent_restraints_adam.md

Requires chem_data + torch. Uses ``Bridge(memory=True)`` (same pack/enqueue
protocol as Redis + ``phridge-cctbx-worker``).
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import numpy as np

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

DEFAULT_MD = HERE / "latent_restraints_adam.md"
N_RESIDUES = 10
DISTORT_SIGMA = 0.35
DISTORT_SEED = 0
ENCODER_SEED = 7
ADAM_STEPS = 200
ADAM_LR = 5e-2
LATENT_DIM = 64
IN_DIM = 15  # ALA: N, CA, C, O, CB


@dataclass
class DemoLog:
    title: str
    checks: list[tuple[bool, str]] = field(default_factory=list)
    sections: list[str] = field(default_factory=list)
    failed: bool = False
    summary_extra: list[tuple[str, str]] = field(default_factory=list)
    # set in main(); used in Summary table
    blurb: str = (
        "Torch-native Adam on latents; CCTBX supplies E, ∂E/∂x, and "
        "restraint stats through phridge so the two play nice."
    )

    def heading(self, text: str) -> None:
        self.sections.append(f"\n## {text}\n\n")

    def para(self, text: str) -> None:
        self.sections.append(f"{text}\n\n")

    def code(self, source: str, lang: str = "python") -> None:
        self.sections.append(f"```{lang}\n{source.rstrip()}\n```\n\n")

    def output(self, text: str) -> None:
        self.sections.append(f"**Output:**\n\n```text\n{text.rstrip()}\n```\n\n")

    def table(self, headers: list[str], rows: list[list[str]]) -> None:
        self.sections.append("| " + " | ".join(headers) + " |\n")
        self.sections.append("| " + " | ".join("---" for _ in headers) + " |\n")
        for row in rows:
            self.sections.append("| " + " | ".join(row) + " |\n")
        self.sections.append("\n")

    def check(self, ok: bool, label: str, detail: str = "") -> None:
        self.checks.append((ok, label if not detail else f"{label} — {detail}"))
        mark = "PASS" if ok else "FAIL"
        line = f"**{mark}** `{label}`"
        if detail:
            line += f" — {detail}"
        self.sections.append(f"- {line}\n")
        if not ok:
            self.failed = True
        print(f"[{mark}] {label}" + (f" — {detail}" if detail else ""))

    def render(self) -> str:
        stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        n_ok = sum(1 for ok, _ in self.checks if ok)
        n = len(self.checks)
        status = "all checks passed" if n_ok == n and n else f"{n_ok}/{n} checks passed"
        lines = [
            f"# {self.title}\n",
            f"_Generated by `examples/latent_restraints_adam.py` on {stamp}. {status}._\n",
            "\n## Summary\n",
            "\n| | |\n|---|---|\n",
            f"| Point | {self.blurb} |\n",
            "| Driver | torch (Adam on 64-D residue latents) |\n",
            "| Loss / grads / stats | CCTBX `energies_sites` via phridge |\n",
            "| Encoder | fixed invertible 2-layer MLP |\n",
        ]
        for k, v in self.summary_extra:
            lines.append(f"| {k} | {v} |\n")
        lines.extend(
            [
                f"| Checks | **{n_ok}/{n}** passed |\n",
                f"| Result | **{'OK' if not self.failed else 'FAILED'}** |\n",
                "\n### Checklist\n",
            ]
        )
        for ok, label in self.checks:
            lines.append(f"- [{'x' if ok else ' '}] {label}\n")
        lines.append("\n")
        lines.extend(self.sections)
        return "".join(lines)

    def write(self, path: Path) -> None:
        path.write_text(self.render(), encoding="utf-8")
        print(f"wrote {path}")


def require_monomer_library(log: DemoLog) -> None:
    from mmtbx.monomer_library import server as mon_server

    path = mon_server.find_mon_lib_file(relative_path_components=["list", "mon_lib_list.cif"])
    log.check(path is not None, "monomer library (chem_data) available", path or "not found")
    if path is None:
        raise SystemExit("chem_data missing — run: make chem-data")


def helix_pdb(n_res: int) -> str:
    from mmtbx.secondary_structure.build import ss_idealization as ssb

    helix = ssb.secondary_structure_from_sequence(ssb.alpha_helix_str, "A" * n_res)
    return (
        "CRYST1  100.000  100.000  100.000  90.00  90.00  90.00 P 1           1\n"
        + helix.as_pdb_string()
    )


def _fmt(x: float, *, digits: int = 6) -> str:
    return f"{x:.{digits}g}"


def _term_map(stats: Optional[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    if not stats:
        return {}
    return {str(t["name"]): t for t in stats.get("terms") or [] if isinstance(t, dict) and "name" in t}


def residual_table_rows(
    before: Optional[dict[str, Any]],
    after: Optional[dict[str, Any]],
) -> list[list[str]]:
    bmap, amap = _term_map(before), _term_map(after)
    names: list[str] = []
    for src in (bmap, amap):
        for name in src:
            if name not in names:
                names.append(name)
    rows: list[list[str]] = []
    for name in names:
        bt, at = bmap.get(name, {}), amap.get(name, {})
        n = int(at.get("n") or bt.get("n") or 0)
        rb = float(bt.get("residual_sum", 0.0) or 0.0)
        ra = float(at.get("residual_sum", 0.0) or 0.0)
        if n == 0 and rb == 0.0 and ra == 0.0:
            continue
        ratio = (ra / rb) if rb else float("nan")
        rows.append(
            [
                name,
                str(n),
                _fmt(rb),
                _fmt(ra),
                _fmt(ratio, digits=4) if np.isfinite(ratio) else "—",
            ]
        )
    tb = float((before or {}).get("target", float("nan")))
    ta = float((after or {}).get("target", float("nan")))
    ratio_t = (ta / tb) if tb else float("nan")
    rows.append(
        [
            "**total**",
            str(int((after or before or {}).get("number_of_restraints", 0) or 0)),
            f"**{_fmt(tb)}**",
            f"**{_fmt(ta)}**",
            f"**{_fmt(ratio_t, digits=4)}**" if np.isfinite(ratio_t) else "—",
        ]
    )
    return rows


def deviation_table_rows(
    before: Optional[dict[str, Any]],
    after: Optional[dict[str, Any]],
) -> list[list[str]]:
    labels = [
        ("bond_A", "bond (Å)"),
        ("angle_deg", "angle (°)"),
        ("dihedral_deg", "dihedral (°)"),
        ("chirality", "chirality"),
        ("planarity_A", "planarity (Å)"),
        ("nonbonded_A", "nonbonded (Å)"),
    ]
    bdev = (before or {}).get("deviations") or {}
    adev = (after or {}).get("deviations") or {}
    rows: list[list[str]] = []
    for key, label in labels:
        bd, ad = bdev.get(key), adev.get(key)
        if not bd and not ad:
            continue
        bd = bd or {}
        ad = ad or {}
        n = int(ad.get("n") or bd.get("n") or 0)
        n_cell = str(n) if n else "—"
        rows.append(
            [
                label,
                n_cell,
                _fmt(float(bd.get("rms", float("nan")))),
                _fmt(float(ad.get("rms", float("nan")))),
                _fmt(float(bd.get("max", float("nan")))),
                _fmt(float(ad.get("max", float("nan")))),
            ]
        )
    return rows


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_MD)
    parser.add_argument("--steps", type=int, default=ADAM_STEPS)
    args = parser.parse_args(argv)

    import torch
    from residue_encoder import ResidueEncoder, residue_slices_from_atoms

    from phridge.client import Bridge, RemoteGeometry, RemoteRestraintBuilder

    log = DemoLog(title="Latent Adam: CCTBX restraints via phridge")
    log.heading("Setup")
    log.para(
        "This example is a **torch-native workflow** that still gets "
        "geometry restraint energy, Cartesian gradients, and Phenix-style "
        "statistics from **CCTBX** — without importing cctbx in the driver "
        "or evaluating a torch copy of the restraint residual. phridge is "
        "the glue: packed sites go out, `E` / `∂E/∂x` / stats come back, "
        "and torch autograd only sees the decoder VJP."
    )
    log.para(
        f"Torch owns Adam on a **fixed invertible** per-residue encoder "
        f"({IN_DIM}-D ALA coords ↔ {LATENT_DIM}-D). CCTBX owns a live GRM "
        f"behind ``restraints_handle`` and evaluates ``energies_sites``. "
        f"Every science hop is ``Bridge.call`` (same protocol as Redis + "
        f"``phridge-cctbx-worker``)."
    )
    log.code(
        """\
built = RemoteRestraintBuilder(bridge).build(pdb_string=pdb)
geo = RemoteGeometry.from_build(bridge, built)
z = encoder.encode_sites(xyz_scrambled, slices).detach().requires_grad_(True)
opt = torch.optim.Adam([z], lr=...)
for _ in range(steps):
    xyz = encoder.decode_sites(z, ...)
    E, g_x = geo.energy_and_gradients(xyz.detach().numpy())  # CCTBX via phridge
    (encoder.decode_sites(z, ...) * g_x_t).sum().backward()
    opt.step(); opt.zero_grad()
# geo.last_target["stats"]  → residual sums + RMS deviations
"""
    )
    require_monomer_library(log)

    bridge = Bridge(memory=True, timeout=120)
    pdb = helix_pdb(N_RESIDUES)

    log.heading("1. CCTBX build (via phridge) — keep GRM alive")
    built = RemoteRestraintBuilder(bridge).build(pdb_string=pdb)
    handle = built.get("restraints_handle")
    log.check(handle is not None and str(handle), "restraints_handle returned", str(handle)[:8] + "…")
    geo = RemoteGeometry.from_build(bridge, built)
    hier = built["hierarchy"]
    n_atoms = int(hier.meta.n_atoms)
    slices = residue_slices_from_atoms(hier.meta.atoms)
    log.check(len(slices) == N_RESIDUES, f"{N_RESIDUES} residue slices", str(len(slices)))
    log.check(all((sl.stop - sl.start) * 3 == IN_DIM for sl in slices), "each residue is 5 atoms (15 coords)")
    restr = built["restraints"]
    log.table(
        ["quantity", "value"],
        [
            ["atoms", str(n_atoms)],
            ["residues", str(len(slices))],
            ["bonds (packed)", str(int(restr.meta.n_bonds))],
            ["angles (packed)", str(int(restr.meta.n_angles))],
            ["dihedrals (packed)", str(int(restr.meta.n_dihedrals))],
            ["restraints_handle", f"`{handle}`"],
        ],
    )

    log.heading("2. Fixed invertible encoder + scramble")
    encoder = ResidueEncoder(in_dim=IN_DIM, latent_dim=LATENT_DIM, seed=ENCODER_SEED)
    encoder.eval()
    xyz0 = torch.as_tensor(np.asarray(hier.xyz, dtype=np.float64), dtype=torch.float64)
    with torch.no_grad():
        z_round = encoder.encode_sites(xyz0, slices)
        xyz_back = encoder.decode_sites(z_round, n_atoms=n_atoms, residue_slices=slices, template_xyz=xyz0)
        round_err = float((xyz_back - xyz0).abs().max())
    log.check(round_err < 1e-8, "encode→decode round-trip", f"max|Δ|={round_err:.3g}")

    rng = np.random.default_rng(DISTORT_SEED)
    noise = rng.normal(0.0, DISTORT_SIGMA, size=xyz0.shape)
    xyz_scr = torch.as_tensor(xyz0.numpy() + noise, dtype=torch.float64)
    with torch.no_grad():
        z = encoder.encode_sites(xyz_scr, slices).detach().clone().requires_grad_(True)

    e0, g0 = geo.energy_and_gradients(xyz_scr.numpy())
    stats0 = dict(geo.last_target.get("stats") or {})
    log.check(np.isfinite(e0), "CCTBX energy at scrambled start", f"{e0:.6g}")
    log.check(g0.shape == (n_atoms, 3), "sites_grad shape", str(g0.shape))
    log.check(bool(stats0.get("terms")), "CCTBX stats returned with energy_grad")
    g0_norm = float(np.linalg.norm(g0))
    log.table(
        ["metric", "scrambled"],
        [
            ["E (CCTBX target)", _fmt(e0)],
            ["‖∂E/∂x‖", _fmt(g0_norm)],
            ["n restraints", str(int(stats0.get("number_of_restraints", 0) or 0))],
        ],
    )

    log.heading("3. Adam on latents (loss/grads from CCTBX through phridge)")
    opt = torch.optim.Adam([z], lr=ADAM_LR)
    history: list[dict[str, float]] = []
    e_prev = e0
    for step in range(int(args.steps)):
        xyz = encoder.decode_sites(z, n_atoms=n_atoms, residue_slices=slices, template_xyz=xyz_scr)
        e, g_x = geo.energy_and_gradients(xyz.detach().numpy())
        g_t = torch.as_tensor(g_x, dtype=torch.float64)
        xyz_t = encoder.decode_sites(z, n_atoms=n_atoms, residue_slices=slices, template_xyz=xyz_scr)
        opt.zero_grad(set_to_none=True)
        (xyz_t * g_t).sum().backward()
        opt.step()
        if step % max(args.steps // 10, 1) == 0 or step + 1 == args.steps:
            gnorm = float(np.linalg.norm(g_x))
            history.append(
                {
                    "step": float(step),
                    "E": float(e),
                    "g_norm": gnorm,
                    "dE": float(e - e_prev),
                    "ratio": float(e / e0) if e0 else float("nan"),
                }
            )
            print(f"  step {step:4d}  E={e:.6g}  ‖g‖={gnorm:.6g}")
            e_prev = e

    xyz_final = (
        encoder.decode_sites(z.detach(), n_atoms=n_atoms, residue_slices=slices, template_xyz=xyz_scr)
        .detach()
        .numpy()
    )
    e_final, g_final = geo.energy_and_gradients(xyz_final)
    stats_f = dict(geo.last_target.get("stats") or {})
    g_final_norm = float(np.linalg.norm(g_final))

    log.check(e_final < e0, "latent Adam decreased CCTBX energy", f"{e_final:.6g} < {e0:.6g}")
    log.check(e_final < 0.5 * e0, "energy dropped by >2×", f"{e_final:.6g} vs {e0:.6g}")
    log.check(bool(stats_f.get("terms")), "CCTBX final stats present")

    log.summary_extra.extend(
        [
            ("E before → after", f"{_fmt(e0)} → {_fmt(e_final)}"),
            ("after / before", _fmt(e_final / e0, digits=4) if e0 else "—"),
            ("‖g‖ before → after", f"{_fmt(g0_norm)} → {_fmt(g_final_norm)}"),
            ("Adam steps", str(int(args.steps))),
            ("lr", _fmt(ADAM_LR, digits=3)),
        ]
    )

    log.para(
        "History sampled every ~10% of steps. **E** and **‖g‖** are from CCTBX "
        "`energies_sites` (via phridge). **ΔE** is change since the previous "
        "logged row; **E/E₀** is relative to the scrambled start."
    )
    log.table(
        ["step", "E", "‖∂E/∂x‖", "ΔE", "E/E₀"],
        [
            [
                str(int(h["step"])),
                _fmt(h["E"]),
                _fmt(h["g_norm"]),
                _fmt(h["dE"]),
                _fmt(h["ratio"], digits=4),
            ]
            for h in history
        ],
    )

    log.heading("4. CCTBX restraint statistics (before → after)")
    log.para(
        "Residual sums and proxy counts from the live GRM "
        "(`energies.show` / term residual sums). Same `restraints_handle` "
        "as the Adam loop — still via phridge."
    )
    log.table(
        ["term", "n", "residual before", "residual after", "after/before"],
        residual_table_rows(stats0, stats_f),
    )
    log.para(
        "Geometry deviations from CCTBX helpers "
        "(`bond_deviations`, `angle_deviations`, …): **RMS** and **max** "
        "|delta| (Å or °)."
    )
    log.table(
        ["geometry", "n", "RMS before", "RMS after", "max before", "max after"],
        deviation_table_rows(stats0, stats_f),
    )
    show0 = "\n".join(stats0.get("show") or []) or "(none)"
    showf = "\n".join(stats_f.get("show") or []) or "(none)"
    log.para("CCTBX `energies.show` at **scrambled** start:")
    log.output(show0)
    log.para("CCTBX `energies.show` after **latent Adam**:")
    log.output(showf)
    log.para(
        "Production: Redis + `phridge-cctbx-worker` (build + energy_grad). "
        "``restraints_handle`` is process-local to that CCTBX worker."
    )

    log.heading("Done")
    log.para(
        "Takeaway: drive optimization in **torch** (custom latents, Adam, "
        "autograd), keep the **cctbx** restraint engine authoritative, and "
        "let phridge make the two play nice — pack/unpack, route to the "
        "CCTBX runtime, and surface the same residual / RMS stats you "
        "would print from `energies.show` in Phenix."
    )
    log.write(args.output)
    return 1 if log.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
