#!/usr/bin/env python3
"""cctbx → phridge Redis → torch minimize → cctbx hierarchy.

Compares torch ``lbfgs``, ``adam``, ``adamw``, and ``sgd`` on a distorted
ideal 30-residue poly-Ala α-helix and writes a markdown code-demo log::

    python examples/restraint_minimization.py
    # → examples/restraint_minimization.md

Requires chem_data (``make chem-data``) and torch.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
from libtbx.utils import null_out
from scitbx.array_family import flex
import iotbx.pdb
import mmtbx.model
from mmtbx.secondary_structure.build import ss_idealization as ssb

from phridge.client import Bridge, RemoteGeometry

HERE = Path(__file__).resolve().parent
DEFAULT_MD = HERE / "restraint_minimization.md"
N_RESIDUES = 30
N_ATOMS_EXPECTED = 5 * N_RESIDUES  # ALA: N, CA, C, O, CB
DISTORT_SIGMA = 0.35  # Å Gaussian noise per coordinate
DISTORT_SEED = 0

# Tuned so first-order methods reach E≈LBFGS on the helix (with schedules).
OPTIMIZER_RUNS: list[dict[str, Any]] = [
    {"optimizer": "lbfgs", "max_iterations": 100, "lr": None, "schedule": None, "momentum": 0.0},
    {
        "optimizer": "adam",
        "max_iterations": 2000,
        "lr": 0.1,
        "lr_min": 1e-4,
        "schedule": "cosine",
        "momentum": 0.0,
    },
    {
        "optimizer": "adam",
        "max_iterations": 3000,
        "lr": 0.15,
        "lr_min": 1e-3,
        "schedule": "triangular",
        "momentum": 0.0,
    },
    {
        "optimizer": "adamw",
        "max_iterations": 4000,
        "lr": 0.2,
        "lr_min": 1e-4,
        "schedule": "cosine",
        "momentum": 0.0,
    },
    {
        "optimizer": "sgd",
        "max_iterations": 4000,
        "lr": 0.02,
        "lr_min": 1e-4,
        "schedule": "cosine",
        "momentum": 0.9,
    },
    {
        "optimizer": "sgd",
        "max_iterations": 4000,
        "lr": 0.03,
        "lr_min": 5e-4,
        "schedule": "triangular",
        "momentum": 0.9,
    },
]


@dataclass
class DemoLog:
    title: str
    checks: list[tuple[bool, str]] = field(default_factory=list)
    sections: list[str] = field(default_factory=list)
    failed: bool = False

    def heading(self, text: str) -> None:
        self.sections.append(f"\n## {text}\n\n")

    def para(self, text: str) -> None:
        self.sections.append(f"{text}\n\n")

    def code(self, source: str, lang: str = "python") -> None:
        self.sections.append(f"```{lang}\n{source.rstrip()}\n```\n\n")

    def output(self, text: str) -> None:
        self.sections.append(f"**Output:**\n\n```text\n{text.rstrip()}\n```\n\n")

    def table(self, headers: list[str], rows: list[list[str]]) -> None:
        self.sections.append("| " + " | ".join(headers) + " |\n")
        self.sections.append("| " + " | ".join("---" for _ in headers) + " |\n")
        for row in rows:
            self.sections.append("| " + " | ".join(row) + " |\n")
        self.sections.append("\n")

    def check(self, ok: bool, label: str, detail: str = "") -> None:
        self.checks.append((ok, label if not detail else f"{label} — {detail}"))
        mark = "PASS" if ok else "FAIL"
        line = f"**{mark}** `{label}`"
        if detail:
            line += f" — {detail}"
        self.sections.append(f"- {line}\n")
        if not ok:
            self.failed = True
        print(f"[{mark}] {label}" + (f" — {detail}" if detail else ""))

    def render(self) -> str:
        stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        n_ok = sum(1 for ok, _ in self.checks if ok)
        n = len(self.checks)
        status = "all checks passed" if n_ok == n and n else f"{n_ok}/{n} checks passed"
        lines = [
            f"# {self.title}\n",
            f"_Generated by `examples/restraint_minimization.py` on {stamp}. {status}._\n",
            "\n## Summary\n",
            "\n| | |\n|---|---|\n",
            "| Flow | cctbx → Redis pack → torch minimize → cctbx |\n",
            "| Optimizers | LBFGS, Adam, AdamW, SGD |\n",
            f"| Checks | **{n_ok}/{n}** passed |\n",
            f"| Result | **{'OK' if not self.failed else 'FAILED'}** |\n",
            "\n### Checklist\n",
        ]
        for ok, label in self.checks:
            lines.append(f"- [{'x' if ok else ' '}] {label}\n")
        lines.append("\n")
        lines.extend(self.sections)
        return "".join(lines)

    def write(self, path: Path) -> None:
        path.write_text(self.render(), encoding="utf-8")
        print(f"wrote {path}")


def require_monomer_library(log: DemoLog) -> str:
    from mmtbx.monomer_library import server as mon_server

    path = mon_server.find_mon_lib_file(relative_path_components=["list", "mon_lib_list.cif"])
    log.check(path is not None, "monomer library (chem_data) available", path or "not found")
    if path is None:
        raise SystemExit("chem_data missing — run: make chem-data")
    return path


def _distorted_model():
    """Ideal poly-Ala α-helix + local Gaussian noise (not a rigid shift)."""
    helix = ssb.secondary_structure_from_sequence(ssb.alpha_helix_str, "A" * N_RESIDUES)
    pdb_str = (
        "CRYST1  100.000  100.000  100.000  90.00  90.00  90.00 P 1           1\n"
        + helix.as_pdb_string()
    )
    model = mmtbx.model.manager(
        model_input=iotbx.pdb.input(source_info=None, lines=pdb_str.split("\n")),
        log=null_out(),
    )
    model.process(make_restraints=True)
    hierarchy = model.get_hierarchy()
    grm = model.get_restraints_manager().geometry
    sites0 = hierarchy.atoms().extract_xyz().deep_copy()
    xyz = np.asarray(list(sites0), dtype=np.float64)
    noise = np.random.default_rng(DISTORT_SEED).normal(0.0, DISTORT_SIGMA, size=xyz.shape)
    sites = flex.vec3_double(xyz + noise)
    hierarchy.atoms().set_xyz(sites)
    return hierarchy, grm, sites0, sites


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_MD)
    args = parser.parse_args(argv)

    log = DemoLog(title="RemoteGeometry.minimize — LBFGS / Adam / AdamW / SGD")
    log.heading("Setup")
    log.para(
        f"Same distorted **{N_RESIDUES}-residue poly-Ala α-helix** for every run "
        f"(ideal `ss_idealization` geometry + σ={DISTORT_SIGMA} Å Gaussian noise). "
        "`RemoteGeometry.minimize` packs cctbx hierarchy + restraints through Redis; "
        "the worker runs a **torch.optim** algorithm; the client blocks and returns "
        "a cctbx hierarchy."
    )
    log.code(
        """\
geo = RemoteGeometry(bridge, hierarchy, restraints_manager)
for name in ("lbfgs", "adam", "adamw", "sgd"):
    hierarchy_out = geo.minimize(max_iterations=..., optimizer=name, lr=...)
"""
    )
    require_monomer_library(log)

    log.heading("1. cctbx molecule + restraints")
    hierarchy, grm, sites0, sites_distorted = _distorted_model()
    n_res = hierarchy.overall_counts().n_residues
    log.output(
        f"molecule=ideal poly-Ala α-helix ({N_RESIDUES} ALA)\n"
        f"atoms={hierarchy.atoms().size()}  residues={n_res}\n"
        f"type(grm)={type(grm).__module__}.{type(grm).__name__}\n"
        f"distortion = N(0, {DISTORT_SIGMA}²) Å per coordinate (seed={DISTORT_SEED})"
    )
    log.check(
        hierarchy.atoms().size() == N_ATOMS_EXPECTED,
        f"cctbx hierarchy has {N_ATOMS_EXPECTED} atoms",
        f"got {hierarchy.atoms().size()}",
    )
    log.check(n_res == N_RESIDUES, f"cctbx hierarchy has {N_RESIDUES} residues", f"got {n_res}")

    log.heading("2. Compare torch optimizers via RemoteGeometry")
    log.code(
        """\
bridge = Bridge(memory=True)  # in-process; use redis_url= for a live server
geo = RemoteGeometry(bridge, hierarchy, grm)

# each optimizer starts from the same distorted sites
hierarchy_out = geo.minimize(
    sites_cart=sites_distorted,
    max_iterations=...,
    optimizer="lbfgs" | "adam" | "adamw" | "sgd",
    lr=...,
)"""
    )
    bridge = Bridge(memory=True, timeout=300)
    geo = RemoteGeometry(bridge, hierarchy, grm)
    e0 = geo.energy(sites_cart=sites_distorted)
    log.check(e0 > 1.0, "remote energy (distorted) is large", f"{e0:.6g}")

    rows: list[list[str]] = []
    results: list[dict[str, Any]] = []
    for run in OPTIMIZER_RUNS:
        name = run["optimizer"]
        hierarchy.atoms().set_xyz(sites_distorted)
        out = geo.minimize(
            sites_cart=sites_distorted,
            max_iterations=int(run["max_iterations"]),
            optimizer=name,
            lr=run.get("lr"),
            lr_min=run.get("lr_min"),
            schedule=run.get("schedule"),
            momentum=float(run.get("momentum") or 0.0),
        )
        tgt = dict(geo.last_target or {})
        before = float(tgt["before"])
        after = float(tgt["after"])
        ratio = after / before if before else float("nan")
        label = name
        if run.get("schedule") and run["schedule"] not in (None, "none"):
            label = f"{name}+{run['schedule']}"
        results.append({"name": name, "label": label, "tgt": tgt, "out": out, "ratio": ratio, "run": run})
        rows.append(
            [
                f"`{label}`",
                str(run["max_iterations"]),
                "—" if run.get("lr") is None else f"{run['lr']:g}",
                str(run.get("schedule") or "none"),
                f"{run.get('momentum') or 0:g}",
                f"{before:.6g}",
                f"{after:.6g}",
                f"{ratio:.4g}",
                str(int(tgt.get("n_steps", 0))),
                str(int(tgt.get("n_calls", tgt.get("n_iter", 0)))),
                f"{float(tgt.get('n_calls', 0)) / max(float(tgt.get('n_steps', 1)), 1):.2f}",
                f"{float(tgt.get('optimizer_state_mb', 0)):.4g}",
                f"{float(tgt.get('rss_delta_mb', 0)):.3g}",
            ]
        )
        print(
            f"{label}: {before:.6g} -> {after:.6g}  "
            f"(steps={tgt.get('n_steps')}, calls={tgt.get('n_calls')}, "
            f"opt_state={tgt.get('optimizer_state_mb'):.4g} MiB, "
            f"rssΔ={tgt.get('rss_delta_mb'):.3g} MiB)"
        )

    log.para(
        "Each row starts from the **same** distorted coordinates. "
        "**n_steps** = optimizer iterations. "
        "**n_calls** = loss(+grad) evaluations (LBFGS closures include strong-Wolfe line search). "
        "**opt_state MiB** = torch optimizer state tensors. "
        "**rssΔ MiB** = process VmRSS change over the minimize call."
    )
    log.table(
        [
            "optimizer",
            "max_iter",
            "lr",
            "schedule",
            "mom",
            "E before",
            "E after",
            "after/before",
            "n_steps",
            "n_calls",
            "calls/step",
            "opt_state MiB",
            "rssΔ MiB",
        ],
        rows,
    )

    log.heading("3. Call-count benchmark")
    log.para(
        "How many times the worker evaluates the torch loss (and gradients) "
        "versus how many optimizer steps it takes."
    )
    call_rows = []
    for res in results:
        tgt = res["tgt"]
        steps = int(tgt.get("n_steps", 0))
        calls = int(tgt.get("n_calls", tgt.get("n_iter", 0)))
        call_rows.append(
            [
                f"`{res['label']}`",
                str(steps),
                str(calls),
                f"{calls / max(steps, 1):.2f}",
                f"{float(tgt['after']):.6g}",
            ]
        )
    log.table(
        ["optimizer", "n_steps", "n_calls (closures / loss evals)", "calls/step", "E after"],
        call_rows,
    )

    log.heading("4. Memory benchmark")
    log.para(
        "**optimizer_state_mb** is the size of tensors stored in `torch.optim` state "
        "(LBFGS history vs Adam/AdamW moments vs SGD velocity). "
        "**rss_delta_mb** is the change in process resident set during that minimize. "
        "**cuda_peak_mb** is zero on CPU."
    )
    mem_rows = []
    for res in results:
        tgt = res["tgt"]
        mem_rows.append(
            [
                f"`{res['label']}`",
                f"{float(tgt.get('optimizer_state_mb', 0)):.6g}",
                f"{float(tgt.get('rss_before_mb', 0)):.3g}",
                f"{float(tgt.get('rss_after_mb', 0)):.3g}",
                f"{float(tgt.get('rss_delta_mb', 0)):.3g}",
                f"{float(tgt.get('cuda_peak_mb', 0)):.3g}",
            ]
        )
    log.table(
        [
            "optimizer",
            "opt_state MiB",
            "rss before",
            "rss after",
            "rss Δ",
            "cuda peak Δ",
        ],
        mem_rows,
    )
    for res in results:
        log.check(
            float(res["tgt"].get("optimizer_state_mb", -1)) >= 0.0,
            f"{res['label']}: optimizer_state_mb reported",
            f"{res['tgt'].get('optimizer_state_mb')} MiB",
        )

    lbfgs = next((r for r in results if r["name"] == "lbfgs"), None)
    if lbfgs is not None:
        steps = int(lbfgs["tgt"].get("n_steps", 0))
        calls = int(lbfgs["tgt"].get("n_calls", 0))
        log.check(
            calls >= steps,
            "lbfgs: closure calls >= LBFGS iterations",
            f"n_calls={calls} n_steps={steps}",
        )
        if steps > 0:
            log.check(
                calls > steps,
                "lbfgs: line search makes extra closure calls",
                f"calls/step={calls / steps:.2f}",
            )
    for res in results:
        if res["name"] in ("adam", "adamw", "sgd"):
            steps = int(res["tgt"].get("n_steps", 0))
            calls = int(res["tgt"].get("n_calls", 0))
            log.check(
                calls == steps,
                f"{res['label']}: one loss call per step",
                f"n_calls={calls} n_steps={steps}",
            )

    for res in results:
        name = res["name"]
        tgt = res["tgt"]
        log.check(tgt.get("optimizer") == name, f"{name}: worker optimizer", str(tgt.get("optimizer")))
        log.check(
            float(tgt["after"]) < float(tgt["before"]),
            f"{name}: energy decreased",
            f"{tgt['after']:.6g} < {tgt['before']:.6g}",
        )
        # LBFGS should crush the target; first-order methods need only a clear drop.
        if name == "lbfgs":
            log.check(
                float(tgt["after"]) < 0.2 * float(tgt["before"]),
                f"{name}: energy dropped by >5×",
                f"{tgt['after']:.6g} < 0.2×{tgt['before']:.6g}",
            )
        log.check(
            res["out"].atoms().size() == hierarchy.atoms().size(),
            f"{name}: returned cctbx hierarchy atom count",
            str(res["out"].atoms().size()),
        )

    best = min(results, key=lambda r: float(r["tgt"]["after"]))
    leanest = min(results, key=lambda r: float(r["tgt"].get("optimizer_state_mb", 1e9)))
    log.para(
        f"Lowest final energy: **`{best['label']}`** ({float(best['tgt']['after']):.6g}). "
        f"Smallest optimizer state: **`{leanest['label']}`** "
        f"({float(leanest['tgt'].get('optimizer_state_mb', 0)):.4g} MiB)."
    )

    log.heading("Done")
    log.para(
        "Phenix only called `RemoteGeometry.minimize(...)` and waited. "
        "Packing, torch optimization (`LBFGS` / `Adam` / `AdamW` / `SGD`), "
        "and unpacking stayed behind the Bridge."
    )
    log.write(args.output)
    return 1 if log.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
