#!/usr/bin/env python3
"""cctbx → phridge Redis → torch minimize → cctbx hierarchy.

Phenix-facing API::

    geo = RemoteGeometry(bridge, hierarchy, restraints_manager)
    hierarchy_out = geo.minimize(optimizer="lbfgs")  # blocks until worker done

This demo uses an in-process worker (fakeredis loopback) and writes a markdown
code-demo log with checks::

    python examples/restraint_minimization.py
    # → examples/restraint_minimization.md

Requires chem_data for the peptide (``make chem-data``) and torch.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from libtbx.utils import null_out
from scitbx.array_family import flex
import iotbx.pdb
import mmtbx.model

from phridge.client import Bridge, RemoteGeometry
from phridge.redis_store import RedisStore
from phridge.worker.runner import process_envelope

HERE = Path(__file__).resolve().parent
DEFAULT_MD = HERE / "restraint_minimization.md"

PDB = """\
CRYST1   21.937    4.866   23.477  90.00 107.08  90.00 P 1 21 1      2
ATOM      1  N   GLY A   1      -9.009   4.612   6.102  1.00 16.77           N
ATOM      2  CA  GLY A   1      -9.052   4.207   4.651  1.00 16.57           C
ATOM      3  C   GLY A   1      -8.015   3.140   4.419  1.00 16.16           C
ATOM      4  O   GLY A   1      -7.523   2.521   5.381  1.00 16.78           O
ATOM      5  N   ASN A   2      -7.656   2.923   3.155  1.00 15.02           N
ATOM      6  CA  ASN A   2      -6.522   2.038   2.831  1.00 14.10           C
ATOM      7  C   ASN A   2      -5.241   2.537   3.427  1.00 13.13           C
ATOM      8  O   ASN A   2      -4.978   3.742   3.426  1.00 11.91           O
ATOM      9  CB  ASN A   2      -6.346   1.881   1.341  1.00 15.38           C
ATOM     10  CG  ASN A   2      -7.584   1.342   0.692  1.00 14.08           C
ATOM     11  OD1 ASN A   2      -8.025   0.227   1.016  1.00 17.46           O
ATOM     12  ND2 ASN A   2      -8.204   2.155  -0.169  1.00 11.72           N
ATOM     13  N   ASN A   3      -4.438   1.590   3.905  1.00 12.26           N
ATOM     14  CA  ASN A   3      -3.193   1.904   4.589  1.00 11.74           C
ATOM     15  C   ASN A   3      -1.955   1.332   3.895  1.00 11.10           C
ATOM     16  O   ASN A   3      -1.872   0.119   3.648  1.00 10.42           O
ATOM     17  CB  ASN A   3      -3.259   1.378   6.042  1.00 12.15           C
END
"""


class _LoopbackBridge(Bridge):
    """Demo stand-in for redis-server + phridge-worker (in-process)."""

    def call(self, op, timeout=None, **kwargs):
        job_id = self.submit(op, **kwargs)
        envelope = self.store.get_envelope(job_id)
        process_envelope(self.store, envelope, device="cpu")
        return self.result(job_id, timeout=30)


@dataclass
class DemoLog:
    title: str
    checks: list[tuple[bool, str]] = field(default_factory=list)
    sections: list[str] = field(default_factory=list)
    failed: bool = False

    def heading(self, text: str) -> None:
        self.sections.append(f"\n## {text}\n\n")

    def para(self, text: str) -> None:
        self.sections.append(f"{text}\n\n")

    def code(self, source: str, lang: str = "python") -> None:
        self.sections.append(f"```{lang}\n{source.rstrip()}\n```\n\n")

    def output(self, text: str) -> None:
        self.sections.append(f"**Output:**\n\n```text\n{text.rstrip()}\n```\n\n")

    def check(self, ok: bool, label: str, detail: str = "") -> None:
        self.checks.append((ok, label if not detail else f"{label} — {detail}"))
        mark = "PASS" if ok else "FAIL"
        line = f"**{mark}** `{label}`"
        if detail:
            line += f" — {detail}"
        self.sections.append(f"- {line}\n")
        if not ok:
            self.failed = True
        print(f"[{mark}] {label}" + (f" — {detail}" if detail else ""))

    def render(self) -> str:
        stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        n_ok = sum(1 for ok, _ in self.checks if ok)
        n = len(self.checks)
        status = "all checks passed" if n_ok == n and n else f"{n_ok}/{n} checks passed"
        lines = [
            f"# {self.title}\n",
            f"_Generated by `examples/restraint_minimization.py` on {stamp}. {status}._\n",
            "\n## Summary\n",
            "\n| | |\n|---|---|\n",
            "| Flow | cctbx → Redis pack → torch minimize → cctbx |\n",
            f"| Checks | **{n_ok}/{n}** passed |\n",
            f"| Result | **{'OK' if not self.failed else 'FAILED'}** |\n",
            "\n### Checklist\n",
        ]
        for ok, label in self.checks:
            lines.append(f"- [{'x' if ok else ' '}] {label}\n")
        lines.append("\n")
        lines.extend(self.sections)
        return "".join(lines)

    def write(self, path: Path) -> None:
        path.write_text(self.render(), encoding="utf-8")
        print(f"wrote {path}")


def require_monomer_library(log: DemoLog) -> str:
    from mmtbx.monomer_library import server as mon_server

    path = mon_server.find_mon_lib_file(relative_path_components=["list", "mon_lib_list.cif"])
    log.check(path is not None, "monomer library (chem_data) available", path or "not found")
    if path is None:
        raise SystemExit("chem_data missing — run: make chem-data")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_MD)
    parser.add_argument("--optimizer", default="lbfgs", choices=("lbfgs", "adam", "sgd"))
    parser.add_argument("--max-iterations", type=int, default=100)
    args = parser.parse_args(argv)

    log = DemoLog(title="RemoteGeometry.minimize (cctbx → torch worker → cctbx)")
    log.heading("Setup")
    log.para(
        "Spin up a phridge worker (here: in-process loopback). A cctbx product "
        "holds a molecule + restraints. `RemoteGeometry.minimize` packs them "
        "through Redis; the worker runs **torch** `LBFGS` / `Adam` / `SGD`; "
        "the client blocks until done and returns a cctbx hierarchy."
    )
    log.code(
        """\
# production:
#   redis-server
#   phridge-worker --redis-url redis://localhost:6379/0 --device cuda
bridge = Bridge("redis://localhost:6379/0")

geo = RemoteGeometry(bridge, hierarchy, restraints_manager)
hierarchy_out = geo.minimize(max_iterations=100, optimizer="lbfgs")  # blocks
""",
    )
    require_monomer_library(log)

    log.heading("1. cctbx molecule + restraints")
    log.code(
        """\
model = mmtbx.model.manager(model_input=..., log=null_out())
model.process(make_restraints=True)
hierarchy = model.get_hierarchy()
grm = model.get_restraints_manager().geometry
# distort so minimization has work to do
sites = hierarchy.atoms().extract_xyz()
sites += flex.vec3_double([(0.25, -0.15, 0.1)] * sites.size())
hierarchy.atoms().set_xyz(sites)"""
    )
    model = mmtbx.model.manager(
        model_input=iotbx.pdb.input(source_info=None, lines=PDB.split("\n")),
        log=null_out(),
    )
    model.process(make_restraints=True)
    hierarchy = model.get_hierarchy()
    grm = model.get_restraints_manager().geometry
    sites = hierarchy.atoms().extract_xyz()
    sites = sites + flex.vec3_double([(0.25, -0.15, 0.1)] * sites.size())
    hierarchy.atoms().set_xyz(sites)
    log.output(f"atoms={hierarchy.atoms().size()}\ntype(grm)={type(grm).__module__}.{type(grm).__name__}")
    log.check(hierarchy.atoms().size() == 17, "cctbx hierarchy has 17 atoms")

    log.heading("2. RemoteGeometry packs + waits on torch worker")
    log.code(
        f"""\
bridge = Bridge(...)  # Redis
geo = RemoteGeometry(bridge, hierarchy, grm)
hierarchy_out = geo.minimize(
    max_iterations={args.max_iterations},
    optimizer={args.optimizer!r},
)"""
    )
    import fakeredis

    bridge = _LoopbackBridge(store=RedisStore(fakeredis.FakeRedis()), timeout=30)
    geo = RemoteGeometry(bridge, hierarchy, grm)
    e0 = geo.energy()
    log.check(e0 > 1.0, "remote energy (distorted) is large", f"{e0:.6g}")
    hierarchy_out = geo.minimize(
        max_iterations=args.max_iterations,
        optimizer=args.optimizer,
    )
    tgt = geo.last_target or {}
    log.output(
        f"optimizer = {tgt.get('optimizer')}\n"
        f"energy before = {tgt.get('before'):.6g}\n"
        f"energy after  = {tgt.get('after'):.6g}\n"
        f"n_iter = {tgt.get('n_iter')}\n"
        f"type(hierarchy_out) = {type(hierarchy_out).__module__}.{type(hierarchy_out).__name__}\n"
        f"atoms = {hierarchy_out.atoms().size()}"
    )
    log.check(tgt.get("optimizer") == args.optimizer, "worker used requested torch optimizer", str(tgt.get("optimizer")))
    log.check(
        float(tgt.get("after", 1e9)) < 0.2 * float(tgt.get("before", 1.0)),
        "torch minimize dropped energy by >5×",
        f"{tgt.get('after'):.6g} < 0.2×{tgt.get('before'):.6g}",
    )
    log.check(
        hierarchy_out.atoms().size() == hierarchy.atoms().size(),
        "returned cctbx hierarchy atom count",
        str(hierarchy_out.atoms().size()),
    )
    log.check("iotbx" in type(hierarchy_out).__module__ or "hierarchy" in type(hierarchy_out).__module__, "result is a cctbx/iotbx hierarchy")

    log.heading("Done")
    log.para(
        "Phenix only called `RemoteGeometry.minimize(...)` and waited. "
        "Packing, torch optimization, and unpacking stayed behind the Bridge."
    )
    log.write(args.output)
    return 1 if log.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
