#!/usr/bin/env python3
"""Structure-factor server demo: cctbx-feel API, work offloaded to a (remote) GPU worker.

Phenix-side code never needs CUDA. Production points StructureFactorServer at
a Redis URL on a GPU machine; this script uses Bridge(memory=True) so it runs
without redis-server, and still documents the remote layout.

Writes::

    python examples/sf_server_demo.py
    # → examples/sf_server_demo.md
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

# Import cctbx before torch (Boost.Python / MKL ordering).
import cctbx  # noqa: F401
from cctbx import sgtbx, xray  # noqa: E402
from cctbx.array_family import flex  # noqa: E402
from cctbx.development import random_structure  # noqa: E402
import numpy as np  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from phridge.client import StructureFactorServer  # noqa: E402
from phridge.models import SfEngineParams  # noqa: E402

HERE = Path(__file__).resolve().parent
DEFAULT_MD = HERE / "sf_server_demo.md"


@dataclass
class DemoLog:
    title: str
    checks: list[tuple[bool, str]] = field(default_factory=list)
    sections: list[str] = field(default_factory=list)
    failed: bool = False

    def heading(self, text: str) -> None:
        self.sections.append(f"\n## {text}\n\n")

    def para(self, text: str) -> None:
        self.sections.append(f"{text}\n\n")

    def code(self, source: str, lang: str = "python") -> None:
        self.sections.append(f"```{lang}\n{source.rstrip()}\n```\n\n")

    def check(self, ok: bool, label: str, detail: str = "") -> None:
        self.checks.append((ok, label if not detail else f"{label} — {detail}"))
        mark = "PASS" if ok else "FAIL"
        line = f"**{mark}** `{label}`"
        if detail:
            line += f" — {detail}"
        self.sections.append(f"- {line}\n")
        if not ok:
            self.failed = True
        print(f"[{mark}] {label}" + (f" — {detail}" if detail else ""))

    def render(self) -> str:
        stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        n_ok = sum(1 for ok, _ in self.checks if ok)
        n = len(self.checks)
        lines = [
            f"# {self.title}\n",
            f"_Generated by `examples/sf_server_demo.py` on {stamp}. "
            f"{n_ok}/{n} checks passed._\n",
            "\n## Summary\n",
            "\n| | |\n|---|---|\n",
            "| Client | `StructureFactorServer` (cctbx-feel) |\n",
            "| Compute | torch FFT engine (GPU worker in production) |\n",
            "| This run | `StructureFactorServer(memory=True)` in-process |\n",
            f"| Checks | **{n_ok}/{n}** passed |\n",
            f"| Result | **{'OK' if not self.failed else 'FAILED'}** |\n",
            "\n### Checklist\n",
        ]
        for ok, label in self.checks:
            lines.append(f"- [{'x' if ok else ' '}] {label}\n")
        lines.append("\n")
        lines.extend(self.sections)
        return "".join(lines)


def _structure(seed: int = 0):
    import random

    random.seed(seed)
    flex.set_random_seed(seed)
    xs = random_structure.xray_structure(
        space_group_info=sgtbx.space_group_info("P21"),
        elements=["C", "N", "O", "S"] * 2,
        volume_per_atom=50,
        random_u_iso=True,
        random_occupancy=True,
    )
    for sc in xs.scatterers():
        sc.flags.set_grad_site(True)
        sc.flags.set_grad_occupancy(True)
        sc.flags.set_grad_u_iso(True)
    return xs


def main() -> int:
    log = DemoLog(title="Structure-factor server — cctbx API, remote GPU compute")

    log.heading("1. Architecture: Phenix here, GPU somewhere else")
    log.para(
        "Phenix keeps a **cctbx-feel** handle (`StructureFactorServer`). "
        "Structure factors and parameter derivatives run on a **torch worker**, "
        "which can live on **another machine** (a GPU server). Redis is the only "
        "coupling — the Phenix process does not import torch and does not need CUDA."
    )
    log.code(
        """# On the GPU server (often a different host):
redis-server
phridge-worker --redis-url redis://0.0.0.0:6379/0 --device cuda

# On the Phenix workstation:
from phridge.client import StructureFactorServer
sf = StructureFactorServer("redis://gpu-lab.example.edu:6379/0")
""",
        lang="bash",
    )
    log.para(
        "This demo uses `StructureFactorServer(memory=True)` so it runs without "
        "`redis-server`. Swap in the Redis URL above for a real remote GPU box."
    )

    # Prefer CUDA in-process when available so the demo still exercises GPU.
    try:
        import torch

        device = "cuda" if torch.cuda.is_available() else "cpu"
    except ImportError:
        device = "cpu"

    sf = StructureFactorServer(memory=True, device=device)
    params = SfEngineParams(d_min=2.0, quality_factor=1000)
    xs = _structure()
    d_min = 2.0
    ref_fc = xs.structure_factors(d_min=d_min, algorithm="direct").f_calc()

    log.heading("2. F_calc — like from_scatterers(...).f_calc()")
    log.code(
        """f_calc = sf.f_calc(xray_structure, miller_set, d_min=2.0)
# → cctbx miller.array (complex), computed on the SF server
"""
    )
    fc = sf.f_calc(xs, ref_fc, params=params)
    ref = np.array(ref_fc.data())
    mine = np.array(fc.data())
    rel = float(np.abs(ref - mine).max() / max(np.abs(ref).max(), 1e-300))
    log.check(rel < 3e-3, "F_calc matches cctbx direct", f"rel_max={rel:.2e} device={device}")

    log.heading("3. Gradients — like gradients_direct")
    log.code(
        """grads = sf.gradients(xray_structure, miller_set, d_target_d_f_calc, d_min=2.0)
packed = grads.packed()   # packing_order_convention 2 for scitbx.lbfgs
"""
    )
    rng = np.random.default_rng(0)
    dtdf = flex.complex_double(rng.normal(size=fc.size()) + 1j * rng.normal(size=fc.size()))
    ref_g = xray.structure_factors.gradients_direct(
        xray_structure=xs,
        u_iso_refinable_params=None,
        miller_set=ref_fc,
        d_target_d_f_calc=dtdf,
        n_parameters=xs.n_parameters(),
    )
    mine_g = sf.gradients(xs, ref_fc, dtdf, params=params)
    packed_rel = float(
        np.abs(np.array(ref_g.packed()) - np.array(mine_g.packed())).max()
        / max(np.abs(np.array(ref_g.packed())).max(), 1e-300)
    )
    log.check(packed_rel < 5e-2, "packed gradients vs cctbx direct", f"rel_max={packed_rel:.2e}")

    log.heading("4. Target + gradients — one round trip for LBFGS")
    log.code(
        """target, packed = sf.target_and_gradients(
    xray_structure, f_obs, {"name": "ls", "obs_type": "F"}, d_min=2.0
)
"""
    )
    f_obs = ref_fc.amplitudes()
    xs2 = xs.deep_copy_scatterers()
    xs2.shake_sites_in_place(rms_difference=0.1)
    for sc in xs2.scatterers():
        sc.flags.set_grad_site(True)
        sc.flags.set_grad_occupancy(False)
        sc.flags.set_grad_u_iso(False)
    target, packed = sf.target_and_gradients(
        xs2, f_obs, {"name": "ls", "obs_type": "F"}, params=params
    )
    log.check(target > 0, "LS target positive on shaken model", f"target={target:.4e}")
    log.check(len(packed) == xs2.n_parameters(), "packed length == n_parameters", f"n={len(packed)}")

    log.heading("5. Production checklist")
    log.para(
        "1. Start Redis + `phridge-worker --device cuda` **on the GPU host**.\n"
        "2. On Phenix, `StructureFactorServer(\"redis://<gpu-host>:6379/0\")`.\n"
        "3. Call `.f_calc` / `.gradients` / `.target_and_gradients` as if they were local cctbx.\n"
        "4. Keep torch off the Phenix process; keep cctbx off the GPU worker."
    )
    log.para("Full write-up: [docs/sf_server.md](../docs/sf_server.md).")

    DEFAULT_MD.write_text(log.render())
    print(f"wrote {DEFAULT_MD}")
    return 1 if log.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
