#!/usr/bin/env python3
"""Torch-driver demo: CCTBX builds restraints, torch minimizes.

Uses ``Bridge(memory=True)`` so both runtimes run in-process (needs cctbx +
torch + chem_data). Production path: Redis + ``phridge-cctbx-worker`` +
``phridge-worker``.

Writes ``examples/torch_build_restraints.md``.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

DEFAULT_MD = Path(__file__).resolve().parent / "torch_build_restraints.md"
N_RESIDUES = 10
DISTORT_SIGMA = 0.35
DISTORT_SEED = 0


class DemoLog:
    def __init__(self, title: str) -> None:
        self.title = title
        self.checks: list[tuple[bool, str]] = []
        self.sections: list[str] = []
        self.failed = False

    def check(self, ok: bool, label: str, detail: object = "") -> None:
        self.checks.append((ok, f"{label} — {detail}" if detail != "" else label))
        if not ok:
            self.failed = True

    def heading(self, text: str) -> None:
        self.sections.append(f"## {text}\n\n")

    def para(self, text: str) -> None:
        self.sections.append(f"{text}\n\n")

    def code(self, text: str) -> None:
        self.sections.append(f"```python\n{text}\n```\n\n")

    def output(self, text: str) -> None:
        self.sections.append(f"**Output:**\n\n```text\n{text}\n```\n\n")

    def render(self) -> str:
        n = len(self.checks)
        n_ok = sum(1 for ok, _ in self.checks if ok)
        stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        lines = [
            f"# {self.title}\n",
            f"_Generated by `examples/torch_build_restraints.py` on {stamp}. "
            f"{'all checks passed' if not self.failed else 'FAILED'}._\n\n",
            "## Summary\n\n",
            "| | |\n|---|---|\n",
            "| Flow | torch driver → cctbx build restraints → torch minimize |\n",
            f"| Checks | **{n_ok}/{n}** passed |\n",
            f"| Result | **{'OK' if not self.failed else 'FAILED'}** |\n",
            "\n### Checklist\n",
        ]
        for ok, label in self.checks:
            lines.append(f"- [{'x' if ok else ' '}] {label}\n")
        lines.append("\n")
        lines.extend(self.sections)
        return "".join(lines)

    def write(self, path: Path) -> None:
        path.write_text(self.render(), encoding="utf-8")
        print(f"wrote {path}")


def require_monomer_library(log: DemoLog) -> None:
    from mmtbx.monomer_library import server as mon_server

    path = mon_server.find_mon_lib_file(relative_path_components=["list", "mon_lib_list.cif"])
    log.check(path is not None, "monomer library (chem_data) available", path or "not found")
    if path is None:
        raise SystemExit("chem_data missing — run: make chem-data")


def helix_pdb(n_res: int) -> str:
    from mmtbx.secondary_structure.build import ss_idealization as ssb

    helix = ssb.secondary_structure_from_sequence(ssb.alpha_helix_str, "A" * n_res)
    return (
        "CRYST1  100.000  100.000  100.000  90.00  90.00  90.00 P 1           1\n"
        + helix.as_pdb_string()
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_MD)
    args = parser.parse_args(argv)

    from phridge.client import Bridge, RemoteGeometry, RemoteRestraintBuilder
    from phridge.packing_geometry import PackedRestraints
    from phridge.packing_xtal import PackedCartesian, PackedHierarchy

    log = DemoLog(title="Torch driver: build_geometry_restraints → geometry_minimize")
    log.heading("Setup")
    log.para(
        f"Torch-facing flow on a **{N_RESIDUES}-residue poly-Ala α-helix**: "
        "`RemoteRestraintBuilder` calls the **cctbx** runtime to build packed "
        "restraints from a PDB string; `RemoteGeometry.minimize` runs on the "
        "**torch** runtime. This script uses `Bridge(memory=True)`."
    )
    log.code(
        """\
bridge = Bridge(memory=True)
out = RemoteRestraintBuilder(bridge).build(pdb_string=pdb)
geo = RemoteGeometry(bridge, out["hierarchy"], out["restraints"])
sites = geo.minimize(..., update_hierarchy=False)
"""
    )
    require_monomer_library(log)

    pdb = helix_pdb(N_RESIDUES)
    bridge = Bridge(memory=True, timeout=120)

    log.heading("1. CCTBX worker builds restraints")
    built = RemoteRestraintBuilder(bridge).build(pdb_string=pdb)
    hier = built["hierarchy"]
    restr = built["restraints"]
    log.check(isinstance(hier, PackedHierarchy), "hierarchy is PackedHierarchy")
    log.check(isinstance(restr, PackedRestraints), "restraints are PackedRestraints")
    log.check(hier.meta.n_atoms == restr.n_sites, "n_atoms == n_sites", restr.n_sites)
    log.check(restr.bond_i_seqs.size > 0, "bond proxies present", restr.bond_i_seqs.shape[0])
    log.output(f"atoms={hier.meta.n_atoms}  bond_proxies={restr.bond_i_seqs.shape[0]}")

    log.heading("2. Distort + torch minimize")
    xyz = np.asarray(hier.xyz, dtype=np.float64)
    noise = np.random.default_rng(DISTORT_SEED).normal(0.0, DISTORT_SIGMA, size=xyz.shape)
    xyz_d = xyz + noise
    geo = RemoteGeometry(bridge, hier, restr)
    before = geo.energy(sites_cart=xyz_d)
    sites_out = geo.minimize(
        max_iterations=80,
        optimizer="lbfgs",
        sites_cart=xyz_d,
        update_hierarchy=False,
    )
    after = float(geo.last_target["after"])
    log.check(isinstance(sites_out, PackedCartesian), "minimize returned PackedCartesian")
    log.check(after < before, "energy decreased", f"{after:.4g} < {before:.4g}")
    log.check(after < 0.2 * before, "energy dropped by >5×", f"{after:.4g} vs {before:.4g}")
    log.output(
        f"before={before:.6g}\nafter={after:.6g}\n"
        f"n_steps={geo.last_target.get('n_steps')}  n_calls={geo.last_target.get('n_calls')}"
    )

    log.write(args.output)
    return 1 if log.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
