#!/usr/bin/env python3
"""Load LinkML schemas and write JSON Schema + markdown docs.

Committed models in src/phridge/models.py are hand-aligned to the YAML
so Phenix clients do not need LinkML at runtime. After editing
schema/*.yaml, update models.py and run this script.
"""

from __future__ import annotations

import argparse
import sys
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "schema" / "phridge.yaml"
GENERATED = ROOT / "schema" / "generated"
DOCS_SCHEMA = ROOT / "docs" / "schema"

REQUIRED_CLASSES = {
    "JobEnvelope",
    "ObjectRef",
    "CrystalSymmetry",
    "MillerArray",
    "HendricksonLattman",
    "ReflectionFile",
    "CrystalGridding",
    "RealMap",
    "ComplexMap",
    "MapCoefficients",
    "CartesianSites",
    "FractionalSites",
    "Hierarchy",
    "XrayStructure",
    "GeometryRestraints",
    "ModelGeometry",
    "EmMap",
    "OpSpec",
}

JSONSCHEMA_CLASSES = ("JobEnvelope", "CrystalSymmetry", "ObjectRef", "ModelGeometry")


def _load_view():
    from linkml_runtime.utils.schemaview import SchemaView

    return SchemaView(str(SCHEMA))


def check_schema(view) -> None:
    classes = set(view.all_classes())
    missing = REQUIRED_CLASSES - classes
    if missing:
        raise SystemExit("missing classes: " + ", ".join(sorted(missing)))
    print(f"loaded {SCHEMA} version={view.schema.version}")
    print("classes:", ", ".join(sorted(classes)))


def write_jsonschema() -> None:
    from linkml.generators.jsonschemagen import JsonSchemaGenerator

    GENERATED.mkdir(parents=True, exist_ok=True)
    for top in JSONSCHEMA_CLASSES:
        gen = JsonSchemaGenerator(str(SCHEMA), top_class=top)
        path = GENERATED / f"{top}.schema.json"
        path.write_text(gen.serialize())
        print(f"wrote {path.relative_to(ROOT)}")


def write_docs() -> None:
    from linkml.generators.docgen import DocGenerator

    if DOCS_SCHEMA.exists():
        shutil.rmtree(DOCS_SCHEMA)
    DOCS_SCHEMA.mkdir(parents=True, exist_ok=True)
    gen = DocGenerator(
        str(SCHEMA),
        directory=str(DOCS_SCHEMA),
        dialect="python",
        render_imports=True,
        genmeta=False,
    )
    gen.serialize()
    (DOCS_SCHEMA / "README.md").write_text(
        "Generated by `make schema-docs` from `schema/phridge.yaml`. Do not edit by hand.\n"
    )
    print(f"wrote {DOCS_SCHEMA.relative_to(ROOT)}/")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--jsonschema", action="store_true", help="write schema/generated/*.schema.json")
    parser.add_argument("--docs", action="store_true", help="write docs/schema markdown")
    parser.add_argument(
        "--all",
        action="store_true",
        help="jsonschema + docs (default if no flags)",
    )
    args = parser.parse_args()
    do_json = args.jsonschema or args.all or not (args.jsonschema or args.docs)
    do_docs = args.docs or args.all or not (args.jsonschema or args.docs)
    try:
        view = _load_view()
    except ImportError:
        print("linkml-runtime is not installed; pip install 'phridge[dev]'", file=sys.stderr)
        return 1
    check_schema(view)
    if do_json:
        write_jsonschema()
    if do_docs:
        write_docs()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
